drop table if exists users;

drop table if exists categories cascade;

drop table if exists events;



create table if not exists users
(
    id    bigint generated by default as identity not null,
    name  varchar(255)                            not null,
    email varchar(255)                            not null,
    constraint pk_user primary key (id),
    constraint uq_user_email unique (email)
);


create table if not exists categories
(
    id   bigint generated by default as identity not null,
    name varchar(50)                             not null,
    constraint pk_category primary key (id),
    constraint uq_category_name unique (name)
);

create table if not exists events
(
    id                 bigint generated by default as identity not null,
    state              varchar(255)                            not null,
    annotation         varchar(2000)                           not null,
    category_id        bigint references categories (id)       not null,
    description        varchar(7000)                           not null,
    event_date         timestamp                               not null,
    lat                real                                    not null,
    lon                real                                    not null,
    paid               bool                                    not null,
    participants_limit integer                                 not null,
    request_moderation bool                                    not null,
    title              varchar(120)                            not null,
    created_on         timestamp default current_timestamp     not null,
    initiator_id       integer                                 not null,
    published_on       timestamp,
    constraint pk_events primary key (id),
    constraint fk_category_id foreign key (category_id) references categories (id) on delete restrict
);



