version: '3.1'
services:
  stats-server:
    build: stats-service/server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14-alpine
    build: stats-service/server
    ports:
      - "6541:5432"
    container_name: stats-db-container
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

#  ewm-service:
#    build: main-service
#    container_name: main-service-container
#    volumes:
#      - "/etc/timezone:/etc/timezone:ro"
#      - "/etc/localtime:/etc/localtime:ro"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ewm-db
#
#  ewm-db:
#    image: postgres:14-alpine
#    container_name: main-service-db-container
#    volumes:
#      - "/etc/timezone:/etc/timezone:ro"
#      - "/etc/localtime:/etc/localtime:ro"
#    ports:
#      - "6540:5431"
#    environment:
#      - POSTGRES_DB=explore-with-me-main
#      - POSTGRES_USER=explore-with-me-main
#      - POSTGRES_PASSWORD=explore-with-me-main

